name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies ConfigurationService.Hosting
      run: dotnet restore src/ConfigurationService.Hosting/ConfigurationService.Hosting.csproj

    - name: Install dependencies ConfigurationService.Client
      run: dotnet restore src/ConfigurationService.Client/ConfigurationService.Client.csproj
      
    - name: Build ConfigurationService.Hosting
      run: dotnet build src/ConfigurationService.Hosting/ConfigurationService.Hosting.csproj --configuration Release --no-restore

    - name: Build ConfigurationService.Client
      run: dotnet build src/ConfigurationService.Client/ConfigurationService.Client.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test src/ConfigurationService.Test/ConfigurationService.Test.csproj --no-restore --logger "console;verbosity=normal"

    - name: Publish ConfigurationService.Hosting
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/ConfigurationService.Hosting/ConfigurationService.Hosting.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false

    - name: Publish ConfigurationService.Client
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/ConfigurationService.Client/ConfigurationService.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false
